// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PsihoKorak_Platforma.Models;

public partial class Help
{
    public int HelpsId { get; set; }

    public string Note { get; set; }

    public int? PatientId { get; set; }

    public int SessionId { get; set; }

    public int PsychologistId { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual Psychologist Psychologist { get; set; }

    public virtual Session Session { get; set; }
}