// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PsihoKorak_Platforma.Models;

public partial class Medication
{
    public int MedicationId { get; set; }

    public string MedicationName { get; set; }

    public string Dose { get; set; }

    public int MedicationTypeId { get; set; }

    public virtual MedicationType MedicationType { get; set; }
}