// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PsihoKorak_Platforma.Models;

public partial class Record
{
    public int RecordId { get; set; }

    public string RecordText { get; set; }

    public DateTime DateTime { get; set; }

    public int PatientId { get; set; }

    public virtual Patient Patient { get; set; }
}