// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PsihoKorak_Platforma.Models;

public partial class SessionType
{
    public int SessionTypeId { get; set; }

    public string SessionTypeName { get; set; }

    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();
}