// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PsihoKorak_Platforma.Models;

public partial class Use
{
    public int UsesId { get; set; }

    public int PatientId { get; set; }

    public string Dose { get; set; }

    public int MedicationId { get; set; }

    public virtual Medication Medication { get; set; }

    public virtual Patient Patient { get; set; }
}